// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Song struct {
	ID         string `json:"id"`
	Path       string `json:"path"`
	LastUpdate string `json:"lastUpdate"`
}

type SongInput struct {
	ID         *string `json:"id,omitempty"`
	Path       string  `json:"path"`
	LastUpdate *string `json:"lastUpdate,omitempty"`
}
