// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MusicResponse struct {
	Songs           []*Song `json:"songs"`
	TotalItemsCount int     `json:"totalItemsCount"`
}

type Mutation struct {
}

type Playlist struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	LastUpdate   string  `json:"lastUpdate"`
	LastAccessed *string `json:"lastAccessed,omitempty"`
	CoverArt     *string `json:"cover_art,omitempty"`
	Songs        []*Song `json:"songs"`
}

type PlaylistInput struct {
	ID       *string `json:"id,omitempty"`
	Name     string  `json:"name"`
	CoverArt *string `json:"cover_art,omitempty"`
}

type PlaylistResponse struct {
	Playlists       []*Playlist `json:"playlists"`
	TotalItemsCount int         `json:"totalItemsCount"`
}

type Query struct {
}

type SongInput struct {
	ID          *string `json:"id,omitempty"`
	Path        string  `json:"path"`
	Title       *string `json:"title,omitempty"`
	Artist      *string `json:"artist,omitempty"`
	Album       *string `json:"album,omitempty"`
	Genre       *string `json:"genre,omitempty"`
	ReleaseYear *string `json:"release_year,omitempty"`
	CoverArt    *string `json:"cover_art,omitempty"`
}
