// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MusicEntColumns holds the columns for the "music_ent" table.
	MusicEntColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "path", Type: field.TypeString, Unique: true, Size: 500},
		{Name: "last_update", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "artist", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "album", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "genre", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "release_year", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "cover_art", Type: field.TypeString, Nullable: true},
	}
	// MusicEntTable holds the schema information for the "music_ent" table.
	MusicEntTable = &schema.Table{
		Name:       "music_ent",
		Columns:    MusicEntColumns,
		PrimaryKey: []*schema.Column{MusicEntColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "music_path",
				Unique:  false,
				Columns: []*schema.Column{MusicEntColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MusicEntTable,
	}
)

func init() {
	MusicEntTable.Annotation = &entsql.Annotation{
		Table: "music_ent",
	}
}
