// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"
	"webmane_go/ent/music"
	"webmane_go/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMusic = "Music"
)

// MusicMutation represents an operation that mutates the Music nodes in the graph.
type MusicMutation struct {
	config
	op            Op
	typ           string
	id            *int
	_path         *string
	last_update   *time.Time
	title         *string
	artist        *string
	album         *string
	genre         *string
	release_year  *string
	cover_art     *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Music, error)
	predicates    []predicate.Music
}

var _ ent.Mutation = (*MusicMutation)(nil)

// musicOption allows management of the mutation configuration using functional options.
type musicOption func(*MusicMutation)

// newMusicMutation creates new mutation for the Music entity.
func newMusicMutation(c config, op Op, opts ...musicOption) *MusicMutation {
	m := &MusicMutation{
		config:        c,
		op:            op,
		typ:           TypeMusic,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMusicID sets the ID field of the mutation.
func withMusicID(id int) musicOption {
	return func(m *MusicMutation) {
		var (
			err   error
			once  sync.Once
			value *Music
		)
		m.oldValue = func(ctx context.Context) (*Music, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Music.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMusic sets the old Music of the mutation.
func withMusic(node *Music) musicOption {
	return func(m *MusicMutation) {
		m.oldValue = func(context.Context) (*Music, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MusicMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MusicMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MusicMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MusicMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Music.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPath sets the "path" field.
func (m *MusicMutation) SetPath(s string) {
	m._path = &s
}

// Path returns the value of the "path" field in the mutation.
func (m *MusicMutation) Path() (r string, exists bool) {
	v := m._path
	if v == nil {
		return
	}
	return *v, true
}

// OldPath returns the old "path" field's value of the Music entity.
// If the Music object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MusicMutation) OldPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPath: %w", err)
	}
	return oldValue.Path, nil
}

// ResetPath resets all changes to the "path" field.
func (m *MusicMutation) ResetPath() {
	m._path = nil
}

// SetLastUpdate sets the "last_update" field.
func (m *MusicMutation) SetLastUpdate(t time.Time) {
	m.last_update = &t
}

// LastUpdate returns the value of the "last_update" field in the mutation.
func (m *MusicMutation) LastUpdate() (r time.Time, exists bool) {
	v := m.last_update
	if v == nil {
		return
	}
	return *v, true
}

// OldLastUpdate returns the old "last_update" field's value of the Music entity.
// If the Music object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MusicMutation) OldLastUpdate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastUpdate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastUpdate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastUpdate: %w", err)
	}
	return oldValue.LastUpdate, nil
}

// ResetLastUpdate resets all changes to the "last_update" field.
func (m *MusicMutation) ResetLastUpdate() {
	m.last_update = nil
}

// SetTitle sets the "title" field.
func (m *MusicMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *MusicMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Music entity.
// If the Music object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MusicMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ClearTitle clears the value of the "title" field.
func (m *MusicMutation) ClearTitle() {
	m.title = nil
	m.clearedFields[music.FieldTitle] = struct{}{}
}

// TitleCleared returns if the "title" field was cleared in this mutation.
func (m *MusicMutation) TitleCleared() bool {
	_, ok := m.clearedFields[music.FieldTitle]
	return ok
}

// ResetTitle resets all changes to the "title" field.
func (m *MusicMutation) ResetTitle() {
	m.title = nil
	delete(m.clearedFields, music.FieldTitle)
}

// SetArtist sets the "artist" field.
func (m *MusicMutation) SetArtist(s string) {
	m.artist = &s
}

// Artist returns the value of the "artist" field in the mutation.
func (m *MusicMutation) Artist() (r string, exists bool) {
	v := m.artist
	if v == nil {
		return
	}
	return *v, true
}

// OldArtist returns the old "artist" field's value of the Music entity.
// If the Music object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MusicMutation) OldArtist(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldArtist is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldArtist requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldArtist: %w", err)
	}
	return oldValue.Artist, nil
}

// ClearArtist clears the value of the "artist" field.
func (m *MusicMutation) ClearArtist() {
	m.artist = nil
	m.clearedFields[music.FieldArtist] = struct{}{}
}

// ArtistCleared returns if the "artist" field was cleared in this mutation.
func (m *MusicMutation) ArtistCleared() bool {
	_, ok := m.clearedFields[music.FieldArtist]
	return ok
}

// ResetArtist resets all changes to the "artist" field.
func (m *MusicMutation) ResetArtist() {
	m.artist = nil
	delete(m.clearedFields, music.FieldArtist)
}

// SetAlbum sets the "album" field.
func (m *MusicMutation) SetAlbum(s string) {
	m.album = &s
}

// Album returns the value of the "album" field in the mutation.
func (m *MusicMutation) Album() (r string, exists bool) {
	v := m.album
	if v == nil {
		return
	}
	return *v, true
}

// OldAlbum returns the old "album" field's value of the Music entity.
// If the Music object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MusicMutation) OldAlbum(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAlbum is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAlbum requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAlbum: %w", err)
	}
	return oldValue.Album, nil
}

// ClearAlbum clears the value of the "album" field.
func (m *MusicMutation) ClearAlbum() {
	m.album = nil
	m.clearedFields[music.FieldAlbum] = struct{}{}
}

// AlbumCleared returns if the "album" field was cleared in this mutation.
func (m *MusicMutation) AlbumCleared() bool {
	_, ok := m.clearedFields[music.FieldAlbum]
	return ok
}

// ResetAlbum resets all changes to the "album" field.
func (m *MusicMutation) ResetAlbum() {
	m.album = nil
	delete(m.clearedFields, music.FieldAlbum)
}

// SetGenre sets the "genre" field.
func (m *MusicMutation) SetGenre(s string) {
	m.genre = &s
}

// Genre returns the value of the "genre" field in the mutation.
func (m *MusicMutation) Genre() (r string, exists bool) {
	v := m.genre
	if v == nil {
		return
	}
	return *v, true
}

// OldGenre returns the old "genre" field's value of the Music entity.
// If the Music object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MusicMutation) OldGenre(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGenre is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGenre requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGenre: %w", err)
	}
	return oldValue.Genre, nil
}

// ClearGenre clears the value of the "genre" field.
func (m *MusicMutation) ClearGenre() {
	m.genre = nil
	m.clearedFields[music.FieldGenre] = struct{}{}
}

// GenreCleared returns if the "genre" field was cleared in this mutation.
func (m *MusicMutation) GenreCleared() bool {
	_, ok := m.clearedFields[music.FieldGenre]
	return ok
}

// ResetGenre resets all changes to the "genre" field.
func (m *MusicMutation) ResetGenre() {
	m.genre = nil
	delete(m.clearedFields, music.FieldGenre)
}

// SetReleaseYear sets the "release_year" field.
func (m *MusicMutation) SetReleaseYear(s string) {
	m.release_year = &s
}

// ReleaseYear returns the value of the "release_year" field in the mutation.
func (m *MusicMutation) ReleaseYear() (r string, exists bool) {
	v := m.release_year
	if v == nil {
		return
	}
	return *v, true
}

// OldReleaseYear returns the old "release_year" field's value of the Music entity.
// If the Music object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MusicMutation) OldReleaseYear(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReleaseYear is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReleaseYear requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReleaseYear: %w", err)
	}
	return oldValue.ReleaseYear, nil
}

// ClearReleaseYear clears the value of the "release_year" field.
func (m *MusicMutation) ClearReleaseYear() {
	m.release_year = nil
	m.clearedFields[music.FieldReleaseYear] = struct{}{}
}

// ReleaseYearCleared returns if the "release_year" field was cleared in this mutation.
func (m *MusicMutation) ReleaseYearCleared() bool {
	_, ok := m.clearedFields[music.FieldReleaseYear]
	return ok
}

// ResetReleaseYear resets all changes to the "release_year" field.
func (m *MusicMutation) ResetReleaseYear() {
	m.release_year = nil
	delete(m.clearedFields, music.FieldReleaseYear)
}

// SetCoverArt sets the "cover_art" field.
func (m *MusicMutation) SetCoverArt(s string) {
	m.cover_art = &s
}

// CoverArt returns the value of the "cover_art" field in the mutation.
func (m *MusicMutation) CoverArt() (r string, exists bool) {
	v := m.cover_art
	if v == nil {
		return
	}
	return *v, true
}

// OldCoverArt returns the old "cover_art" field's value of the Music entity.
// If the Music object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MusicMutation) OldCoverArt(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCoverArt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCoverArt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCoverArt: %w", err)
	}
	return oldValue.CoverArt, nil
}

// ClearCoverArt clears the value of the "cover_art" field.
func (m *MusicMutation) ClearCoverArt() {
	m.cover_art = nil
	m.clearedFields[music.FieldCoverArt] = struct{}{}
}

// CoverArtCleared returns if the "cover_art" field was cleared in this mutation.
func (m *MusicMutation) CoverArtCleared() bool {
	_, ok := m.clearedFields[music.FieldCoverArt]
	return ok
}

// ResetCoverArt resets all changes to the "cover_art" field.
func (m *MusicMutation) ResetCoverArt() {
	m.cover_art = nil
	delete(m.clearedFields, music.FieldCoverArt)
}

// Where appends a list predicates to the MusicMutation builder.
func (m *MusicMutation) Where(ps ...predicate.Music) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MusicMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MusicMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Music, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MusicMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MusicMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Music).
func (m *MusicMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MusicMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m._path != nil {
		fields = append(fields, music.FieldPath)
	}
	if m.last_update != nil {
		fields = append(fields, music.FieldLastUpdate)
	}
	if m.title != nil {
		fields = append(fields, music.FieldTitle)
	}
	if m.artist != nil {
		fields = append(fields, music.FieldArtist)
	}
	if m.album != nil {
		fields = append(fields, music.FieldAlbum)
	}
	if m.genre != nil {
		fields = append(fields, music.FieldGenre)
	}
	if m.release_year != nil {
		fields = append(fields, music.FieldReleaseYear)
	}
	if m.cover_art != nil {
		fields = append(fields, music.FieldCoverArt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MusicMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case music.FieldPath:
		return m.Path()
	case music.FieldLastUpdate:
		return m.LastUpdate()
	case music.FieldTitle:
		return m.Title()
	case music.FieldArtist:
		return m.Artist()
	case music.FieldAlbum:
		return m.Album()
	case music.FieldGenre:
		return m.Genre()
	case music.FieldReleaseYear:
		return m.ReleaseYear()
	case music.FieldCoverArt:
		return m.CoverArt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MusicMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case music.FieldPath:
		return m.OldPath(ctx)
	case music.FieldLastUpdate:
		return m.OldLastUpdate(ctx)
	case music.FieldTitle:
		return m.OldTitle(ctx)
	case music.FieldArtist:
		return m.OldArtist(ctx)
	case music.FieldAlbum:
		return m.OldAlbum(ctx)
	case music.FieldGenre:
		return m.OldGenre(ctx)
	case music.FieldReleaseYear:
		return m.OldReleaseYear(ctx)
	case music.FieldCoverArt:
		return m.OldCoverArt(ctx)
	}
	return nil, fmt.Errorf("unknown Music field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MusicMutation) SetField(name string, value ent.Value) error {
	switch name {
	case music.FieldPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPath(v)
		return nil
	case music.FieldLastUpdate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastUpdate(v)
		return nil
	case music.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case music.FieldArtist:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetArtist(v)
		return nil
	case music.FieldAlbum:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAlbum(v)
		return nil
	case music.FieldGenre:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGenre(v)
		return nil
	case music.FieldReleaseYear:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReleaseYear(v)
		return nil
	case music.FieldCoverArt:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCoverArt(v)
		return nil
	}
	return fmt.Errorf("unknown Music field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MusicMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MusicMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MusicMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Music numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MusicMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(music.FieldTitle) {
		fields = append(fields, music.FieldTitle)
	}
	if m.FieldCleared(music.FieldArtist) {
		fields = append(fields, music.FieldArtist)
	}
	if m.FieldCleared(music.FieldAlbum) {
		fields = append(fields, music.FieldAlbum)
	}
	if m.FieldCleared(music.FieldGenre) {
		fields = append(fields, music.FieldGenre)
	}
	if m.FieldCleared(music.FieldReleaseYear) {
		fields = append(fields, music.FieldReleaseYear)
	}
	if m.FieldCleared(music.FieldCoverArt) {
		fields = append(fields, music.FieldCoverArt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MusicMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MusicMutation) ClearField(name string) error {
	switch name {
	case music.FieldTitle:
		m.ClearTitle()
		return nil
	case music.FieldArtist:
		m.ClearArtist()
		return nil
	case music.FieldAlbum:
		m.ClearAlbum()
		return nil
	case music.FieldGenre:
		m.ClearGenre()
		return nil
	case music.FieldReleaseYear:
		m.ClearReleaseYear()
		return nil
	case music.FieldCoverArt:
		m.ClearCoverArt()
		return nil
	}
	return fmt.Errorf("unknown Music nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MusicMutation) ResetField(name string) error {
	switch name {
	case music.FieldPath:
		m.ResetPath()
		return nil
	case music.FieldLastUpdate:
		m.ResetLastUpdate()
		return nil
	case music.FieldTitle:
		m.ResetTitle()
		return nil
	case music.FieldArtist:
		m.ResetArtist()
		return nil
	case music.FieldAlbum:
		m.ResetAlbum()
		return nil
	case music.FieldGenre:
		m.ResetGenre()
		return nil
	case music.FieldReleaseYear:
		m.ResetReleaseYear()
		return nil
	case music.FieldCoverArt:
		m.ResetCoverArt()
		return nil
	}
	return fmt.Errorf("unknown Music field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MusicMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MusicMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MusicMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MusicMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MusicMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MusicMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MusicMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Music unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MusicMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Music edge %s", name)
}
