// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"webmane_go/ent/playlist"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Playlist is the model entity for the Playlist schema.
type Playlist struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// LastUpdate holds the value of the "last_update" field.
	LastUpdate time.Time `json:"last_update,omitempty"`
	// LastAccessed holds the value of the "last_accessed" field.
	LastAccessed time.Time `json:"last_accessed,omitempty"`
	// CoverArt holds the value of the "cover_art" field.
	CoverArt string `json:"cover_art,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlaylistQuery when eager-loading is set.
	Edges        PlaylistEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlaylistEdges holds the relations/edges for other nodes in the graph.
type PlaylistEdges struct {
	// Songs holds the value of the songs edge.
	Songs []*Music `json:"songs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SongsOrErr returns the Songs value or an error if the edge
// was not loaded in eager-loading.
func (e PlaylistEdges) SongsOrErr() ([]*Music, error) {
	if e.loadedTypes[0] {
		return e.Songs, nil
	}
	return nil, &NotLoadedError{edge: "songs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Playlist) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playlist.FieldID:
			values[i] = new(sql.NullInt64)
		case playlist.FieldName, playlist.FieldCoverArt:
			values[i] = new(sql.NullString)
		case playlist.FieldLastUpdate, playlist.FieldLastAccessed:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Playlist fields.
func (pl *Playlist) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playlist.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pl.ID = int(value.Int64)
		case playlist.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pl.Name = value.String
			}
		case playlist.FieldLastUpdate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_update", values[i])
			} else if value.Valid {
				pl.LastUpdate = value.Time
			}
		case playlist.FieldLastAccessed:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_accessed", values[i])
			} else if value.Valid {
				pl.LastAccessed = value.Time
			}
		case playlist.FieldCoverArt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_art", values[i])
			} else if value.Valid {
				pl.CoverArt = value.String
			}
		default:
			pl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Playlist.
// This includes values selected through modifiers, order, etc.
func (pl *Playlist) Value(name string) (ent.Value, error) {
	return pl.selectValues.Get(name)
}

// QuerySongs queries the "songs" edge of the Playlist entity.
func (pl *Playlist) QuerySongs() *MusicQuery {
	return NewPlaylistClient(pl.config).QuerySongs(pl)
}

// Update returns a builder for updating this Playlist.
// Note that you need to call Playlist.Unwrap() before calling this method if this Playlist
// was returned from a transaction, and the transaction was committed or rolled back.
func (pl *Playlist) Update() *PlaylistUpdateOne {
	return NewPlaylistClient(pl.config).UpdateOne(pl)
}

// Unwrap unwraps the Playlist entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pl *Playlist) Unwrap() *Playlist {
	_tx, ok := pl.config.driver.(*txDriver)
	if !ok {
		panic("ent: Playlist is not a transactional entity")
	}
	pl.config.driver = _tx.drv
	return pl
}

// String implements the fmt.Stringer.
func (pl *Playlist) String() string {
	var builder strings.Builder
	builder.WriteString("Playlist(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pl.ID))
	builder.WriteString("name=")
	builder.WriteString(pl.Name)
	builder.WriteString(", ")
	builder.WriteString("last_update=")
	builder.WriteString(pl.LastUpdate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_accessed=")
	builder.WriteString(pl.LastAccessed.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("cover_art=")
	builder.WriteString(pl.CoverArt)
	builder.WriteByte(')')
	return builder.String()
}

// Playlists is a parsable slice of Playlist.
type Playlists []*Playlist
